In [9]:
import requests
import json
from matplotlib import pyplot as plt
import pandas as pd
import netCDF4
import fsspec
import xarray as xr

# API

In [80]:
# last available day for solar radiation "20221101"
start = "20221101"
end = "20221101"
location = "latitude=39.46&longitude=-0.3"
parameters = "ALLSKY_SFC_LW_DWN;ALLSKY_KT"
community = "re" # "ag" "sb" "re"
url = f"https://power.larc.nasa.gov/api/temporal/hourly/point?start={start}&end={end}&{location}&community={community}&parameters={parameters}&format=json&user=cam&header=true&time-standard=utc"

In [81]:
response = requests.get(url)
json.loads(response.content)

{'type': 'Feature',
 'geometry': {'type': 'Point', 'coordinates': [-0.3, 39.46, 51.22]},
 'properties': {'parameter': {'ALLSKY_SFC_LW_DWN': {'2022110200': -999.0,
    '2022110201': -999.0,
    '2022110202': -999.0,
    '2022110203': -999.0,
    '2022110204': -999.0,
    '2022110205': -999.0,
    '2022110206': -999.0,
    '2022110207': -999.0,
    '2022110208': -999.0,
    '2022110209': -999.0,
    '2022110210': -999.0,
    '2022110211': -999.0,
    '2022110212': -999.0,
    '2022110213': -999.0,
    '2022110214': -999.0,
    '2022110215': -999.0,
    '2022110216': -999.0,
    '2022110217': -999.0,
    '2022110218': -999.0,
    '2022110219': -999.0,
    '2022110220': -999.0,
    '2022110221': -999.0,
    '2022110222': -999.0,
    '2022110223': -999.0}}},
 'header': {'title': 'NASA/POWER CERES/MERRA2 Native Resolution Hourly Data',
  'api': {'version': 'v2.4.2', 'name': 'POWER Hourly API'},
  'sources': ['ceres'],
  'fill_value': -999.0,
  'start': '20221102',
  'end': '20221102'},
 'messages': [],
 'parameters': {'ALLSKY_SFC_LW_DWN': {'units': 'W/m^2',
   'longname': 'All Sky Surface Longwave Downward Irradiance'}},
 'times': {'data': 1.467, 'process': 0.16}}

In [86]:
# request data availability 
url = "https://power.larc.nasa.gov/api/system/resources/dashboard/Availability"
response = requests.get(url)
json.loads(response.content)

{'sources': {'MERRA2': {'last': '2022/11/01',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15280,
   'percent_processed': 98.98,
   'total_latency': 157,
   'percent_latency': 130.83},
  'GEOS5124': {'last': '2023/04/04',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15434,
   'percent_processed': 99.98,
   'total_latency': 3,
   'percent_latency': 2.5},
  'CERES': {'last': '2022/11/01',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15280,
   'percent_processed': 98.98,
   'total_latency': 157,
   'percent_latency': 130.83},
  'FLASHFLUX': {'last': '2023/04/02',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15432,
   'percent_processed': 99.97,
   'total_latency': 5,
   'percent_latency': 4.17},
  'IMERG-LATE': {'last': '2023/03/20',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15419,
   'percent_processed': 99.88,
   'total_latency': 18,
   'percent_latency': 15.0},
  'IMERG-FINAL': {'last': '2021/09/30',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 14883,
   'percent_processed': 96.41,
   'total_latency': 554,
   'percent_latency': 461.67},
  'LAST': {'last': '2023/04/06',
   'days_ago_date': '2022/12/08',
   'total_days': 15437,
   'total_processed': 15436,
   'percent_processed': 99.99,
   'total_latency': 1,
   'percent_latency': 0.83}}}

# netCDF4 and Xarray

In [22]:
fp='april_data.nc'
nc = netCDF4.Dataset(fp)
nc.summary
# plt.imshow(nc['Temp'][1,:,0,:])
# plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'april_data.nc'

In [14]:
nc.variables;

In [9]:
import xarray as xr

ds = xr.open_dataset('april_data.nc')
df = ds.to_dataframe()

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
T2MDEW,4990464.0,273.669019,20.722342,210.757812,2.594766e+02,277.039062,292.273438,300.015625
QV2M,4990464.0,0.007536,0.006718,0.000000,1.281738e-03,0.005066,0.013916,0.022644
WD2M,4990464.0,172.964077,101.159818,0.000000,8.731250e+01,162.312500,259.562500,360.000000
T2MWET,4990464.0,275.413154,21.269618,210.882812,2.608359e+02,279.585938,294.367188,302.781250
TQV,4990464.0,18.285236,17.023967,0.187500,3.656250e+00,12.375000,29.078125,78.093750
TROPT,4990464.0,209.005343,11.091206,181.867188,1.977266e+02,211.812500,217.320312,258.195312
RHOA,4990464.0,1.215439,0.106762,0.680664,1.159180e+00,1.208984,1.270508,1.548828
TROPQ,4990464.0,0.000018,0.000016,0.000000,0.000000e+00,0.000015,0.000031,0.000671
V2M,4990464.0,0.248270,4.118211,-18.546875,-2.320312e+00,0.078125,2.781250,23.882812
U50M,4990464.0,-0.414774,6.412682,-37.671875,-4.734375e+00,-0.757812,3.828125,25.554688
QV10M,4990464.0,0.007312,0.006524,0.000000,1.220703e-03,0.004944,0.013428,0.021790
V50M,4990464.0,0.346152,5.975038,-26.632812,-3.570312e+00,0.179688,4.171875,31.773438
WD50M,4990464.0,172.822864,101.248745,0.000000,8.693750e+01,161.750000,259.687500,360.000000
U2M,4990464.0,-0.331826,4.483032,-26.375000,-3.351562e+00,-0.359375,2.414062,17.640625
T10M,4990464.0,277.267658,21.885405,211.101562,2.618359e+02,281.726562,296.789062,314.062500
WS10M,4990464.0,6.416281,3.700824,0.000000,3.625000e+00,5.929688,8.437500,32.851562
V10M,4990464.0,0.302329,5.015356,-23.007812,-2.921875e+00,0.156250,3.429688,28.984375
T2M,4990464.0,277.158002,22.125218,210.984375,2.616016e+02,281.679688,296.781250,315.632812
TROPPB,4990464.0,21886.419024,9616.492777,7255.812500,1.182375e+04,22655.875000,29330.062500,72783.000000
DISPH,4990464.0,0.632296,2.868944,0.000000,0.000000e+00,0.000000,0.000000,23.078125
WS50M,4990464.0,7.684027,4.251017,0.000000,4.531250e+00,7.046875,10.117188,38.203125
U10M,4990464.0,-0.375470,5.429427,-32.015625,-3.984375e+00,-0.578125,3.062500,21.843750
TO3,4990464.0,309.801728,68.548285,221.414062,2.610547e+02,274.968750,349.773438,528.507812
RH2M,4990464.0,82.351484,16.800174,2.062500,7.706250e+01,84.625000,94.437500,100.000000
WS2M,4990464.0,5.221884,3.156107,0.000000,2.835938e+00,4.937500,7.039062,27.054688
WD10M,4990464.0,172.840620,101.273388,0.000000,8.700000e+01,161.812500,259.625000,360.000000
PRECTOTCORR,4990464.0,0.000028,0.000120,0.000000,1.764856e-07,0.000003,0.000016,0.011642
FRSEAICE,4990464.0,0.105125,0.289144,0.000000,0.000000e+00,0.000000,0.000000,1.000000
PS,4990464.0,96834.939395,9243.014087,50747.375000,9.764669e+04,100788.000000,101428.812500,103677.375000
TS,4990464.0,277.527382,23.177054,201.429688,2.617734e+02,282.234375,297.562500,329.531250

In [90]:
!wget -O latest.nc https://power-datastore.s3.amazonaws.com/v9/hourly/2022/12/power_901_hourly_20221230_ceres_utc.nc

--2023-04-07 16:30:09--  https://power-datastore.s3.amazonaws.com/v9/hourly/2022/12/power_901_hourly_20221230_ceres_utc.nc
Resolving power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)... 52.218.244.114, 52.92.251.25, 52.218.252.52, ...
Connecting to power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)|52.218.244.114|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60841232 (58M) [application/x-netcdf]
Saving to: ‘latest.nc’

latest.nc           100%[===================>]  58,02M  8,21MB/s    in 8,0s

2023-04-07 16:30:18 (7,22 MB/s) - ‘latest.nc’ saved [60841232/60841232]

In [94]:
ds = xr.open_dataset('latest.nc')
df = ds.to_dataframe()

In [96]:
df.describe()

,ALLSKY_SFC_PAR_TOT,TOA_SW_DWN,ALLSKY_SFC_PAR_DIFF,ALLSKY_SFC_LW_UP,AOD_55_ADJ,ALLSKY_SFC_SW_DIFF,TS_ADJ,CLRSKY_NKT,CLRSKY_SFC_SW_DIRH,CLRSKY_SRF_ALB,...,ALLSKY_SFC_SW_UP,SKY_BRIGHTNESS,CLRSKY_SFC_PAR_DIRH,CLRSKY_SFC_LW_UP,CLRSKY_DAYS,SZA,PW,SRF_ALB_ADJ,ALLSKY_SRF_ALB,AIRMASS
count,1.555200e+06,1.555200e+06,1.555200e+06,1.555200e+06,1.555200e+06,1.555200e+06,1.555200e+06,790529.000000,1.555200e+06,790529.000000,...,1.555200e+06,790529.000000,1.555200e+06,1.555200e+06,1555200,1.555200e+06,1.555200e+06,1.555200e+06,790529.000000,1.555200e+06
mean,8.533770e+01,3.271554e+02,5.108438e+01,3.472754e+02,1.155542e-01,8.323240e+01,2.777384e+02,0.834725,1.961177e+02,0.304369,...,4.776411e+01,1.124777,8.008726e+01,3.465409e+02,0 days 02:57:55.111111111,7.510323e+01,1.730506e+00,1.673123e+38,0.244279,1.771271e+01
std,1.229680e+02,4.217948e+02,7.688606e+01,9.755955e+01,1.352993e-01,1.216239e+02,2.106069e+01,0.119969,2.730464e+02,8.054750,...,1.108651e+02,1.638282,1.157436e+02,9.764707e+01,0 days 07:53:51.885666484,2.037109e+01,1.592267e+00,1.701177e+38,0.280926,1.422781e+01
min,0.000000e+00,0.000000e+00,0.000000e+00,1.071016e+02,0.000000e+00,0.000000e+00,2.087969e+02,0.000000,0.000000e+00,0.000000,...,0.000000e+00,0.023438,0.000000e+00,1.070469e+02,0 days 00:00:00,4.015625e+00,2.343750e-02,0.000000e+00,0.000000,1.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,2.590781e+02,2.343750e-02,0.000000e+00,2.601797e+02,0.757812,0.000000e+00,0.054688,...,0.000000e+00,0.328125,0.000000e+00,2.582266e+02,0 days 00:00:00,6.420312e+01,4.062500e-01,8.593750e-02,0.054688,2.281250e+00
50%,2.273438e+00,2.537500e+01,2.273438e+00,3.540117e+02,8.593750e-02,7.710938e+00,2.814219e+02,0.796875,6.718750e-01,0.140625,...,4.765625e-01,0.554688,2.343750e-02,3.530234e+02,0 days 00:00:00,8.896875e+01,1.156250e+00,8.203125e-01,0.078125,2.324219e+01
75%,1.576250e+02,6.127266e+02,8.262500e+01,4.372266e+02,1.562500e-01,1.362266e+02,2.966250e+02,0.914062,3.884531e+02,0.414062,...,3.037500e+01,1.156250,1.533984e+02,4.366484e+02,0 days 00:00:00,9.000000e+01,2.804688e+00,3.402823e+38,0.375000,3.173438e+01
max,1.400547e+03,1.404477e+03,1.371727e+03,8.480000e+02,2.468750e+00,1.380055e+03,3.527578e+02,1.484375,1.163477e+03,2006.914062,...,8.967734e+02,42.195312,4.750469e+02,8.477266e+02,1 days 00:00:00,9.000000e+01,8.609375e+00,3.402823e+38,0.929688,3.173438e+01

In [121]:
ds["ALLSKY_SFC_PAR_TOT"].sel(time="2022-12-30T15:00",lon=0.5, lat=4.5).values

array(169.2265625)

In [122]:
ds.time

<xarray.DataArray 'time' (time: 24)>
array(['2022-12-30T00:00:00.000000000', '2022-12-30T01:00:00.000000000',
       '2022-12-30T02:00:00.000000000', '2022-12-30T03:00:00.000000000',
       '2022-12-30T04:00:00.000000000', '2022-12-30T05:00:00.000000000',
       '2022-12-30T06:00:00.000000000', '2022-12-30T07:00:00.000000000',
       '2022-12-30T08:00:00.000000000', '2022-12-30T09:00:00.000000000',
       '2022-12-30T10:00:00.000000000', '2022-12-30T11:00:00.000000000',
       '2022-12-30T12:00:00.000000000', '2022-12-30T13:00:00.000000000',
       '2022-12-30T14:00:00.000000000', '2022-12-30T15:00:00.000000000',
       '2022-12-30T16:00:00.000000000', '2022-12-30T17:00:00.000000000',
       '2022-12-30T18:00:00.000000000', '2022-12-30T19:00:00.000000000',
       '2022-12-30T20:00:00.000000000', '2022-12-30T21:00:00.000000000',
       '2022-12-30T22:00:00.000000000', '2022-12-30T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2022-12-30 ... 2022-12-30T23:00:00
Attributes:
    long_name:  time

In [124]:
ds["ALLSKY_SFC_PAR_TOT"].sel(time="2022-12-30T15:00").to_pandas()

lon,-179.5,-178.5,-177.5,-176.5,-175.5,-174.5,-173.5,-172.5,-171.5,-170.5,...,170.5,171.5,172.5,173.5,174.5,175.5,176.5,177.5,178.5,179.5
lat,,,,,,,,,,,,,,,,,,,,,
89.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
88.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
87.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
86.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
85.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
-85.5,159.578125,159.578125,159.578125,159.578125,159.578125,159.578125,159.578125,159.578125,149.546875,149.546875,...,151.828125,151.828125,157.476562,157.476562,157.476562,157.476562,157.476562,157.476562,157.476562,157.476562
-86.5,169.851562,169.851562,169.851562,169.851562,169.851562,169.851562,169.851562,169.851562,168.500000,168.500000,...,168.023438,168.023438,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
-87.5,176.726562,176.726562,176.726562,176.726562,176.726562,176.726562,176.726562,176.726562,184.296875,184.296875,...,179.796875,179.796875,179.273438,179.273438,179.273438,179.273438,179.273438,179.273438,179.273438,179.273438
-88.5,158.796875,158.796875,158.796875,158.796875,158.796875,158.796875,158.796875,158.796875,163.398438,163.398438,...,148.796875,148.796875,157.953125,157.953125,157.953125,157.953125,157.953125,157.953125,157.953125,157.953125
-89.5,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,...,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438,181.023438

# Example from docs

In [58]:
filepath_month = 'https://power-analysis-ready-datastore.s3.amazonaws.com/power_901_monthly_radiation_utc.zarr'
filepath_hour = 'https://power-analysis-ready-datastore.s3.amazonaws.com/power_901_hourly_radiation_utc.zarr'

filepath_mapped_month = fsspec.get_mapper(filepath_month)
ds = xr.open_zarr(store=filepath_mapped_month, consolidated=True)

filepath_mapped_hour = fsspec.get_mapper(filepath_hour)
ds_hour = xr.open_zarr(store=filepath_mapped_hour, consolidated=True)

In [29]:
# accesing values of one dimension
ds["time"]
ds["lat"]
ds["lon"];

In [27]:
# accesing specific measurement
ds.AIRMASS # all values in the three coordinates

<xarray.DataArray 'time' ()>
array('2021-12-31T00:00:00.000000000', dtype='datetime64[ns]')

In [50]:
# accesing a variable in a specified range
ds["AIRMASS"].sel(time="2001-01")

<xarray.DataArray 'AIRMASS' (time: 1, lat: 180, lon: 360)>
[64800 values with dtype=float64]
Coordinates:
  * lat      (lat) float64 -89.5 -88.5 -87.5 -86.5 -85.5 ... 86.5 87.5 88.5 89.5
  * lon      (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * time     (time) datetime64[ns] 2001-01-31
Attributes:
    long_name:      Air Mass
    standard_name:  Air_Mass
    units:          dimensionless

In [34]:
# initializing with time series
import numpy as np
import pandas as pd
time = pd.date_range("2000-01-01", freq="H", periods=365 * 24)
bar = xr.Dataset({"foo": ("time", np.arange(365 * 24)), "time": time})

In [54]:
from pympler import asizeof

size = asizeof.asizeof(ds)

print("Total size of my_object in mega bytes:", size / 1e6)

Total size of my_object in mega bytes: 243.669464

/Users/camilo.ramirez/Library/Caches/pypoetry/virtualenvs/data-playground-K_szDW0O-py3.10/lib/python3.10/site-packages/pympler/asizeof.py:690: UserWarning: Iterating '<class 'traitlets.config.loader.Config'>': TypeError("'LazyConfigValue' object is not iterable")
  warnings.warn("Iterating '%s': %r" % (_classof(obj), x))

In [60]:
ds.sizes

Frozen({'time': 456, 'lat': 180, 'lon': 360})

In [59]:
ds_hour.sizes
ds_hour

Frozen({'time': 210408, 'lat': 180, 'lon': 360})

# ETL Workflow

In [14]:
import numpy as np
import pandas as pd
import xarray as xr

import shapely
import json
from shapely.geometry import Point
from shapely.validation import make_valid

In [181]:
# downloads
year = "2022"
month = "05"
day = "08"

datetime = f"{year}{month}{day}"

# month = "0" + str(i + 1)
# month = month[-2:]

url = f"https://power-datastore.s3.amazonaws.com/v9/hourly/{year}/{month}/power_901_hourly_{datetime}_ceres_utc.nc"
url_day = f"https://power-datastore.s3.amazonaws.com/v9/daily/{year}/{month}/power_901_daily_{datetime}_geos5124_utc.nc"
url_hour = f"https://power-datastore.s3.amazonaws.com/v9/hourly/{year}/{month}/power_901_daily_{datetime}_geos5124_utc.nc"
 
# !wget -O latest.nc {url}
!wget -O latest_month_geo.nc {url_day}

--2023-04-10 18:08:00--  https://power-datastore.s3.amazonaws.com/v9/daily/2022/05/power_901_daily_20220508_geos5124_utc.nc
Resolving power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)... 52.92.133.241, 52.218.185.75, 52.92.131.137, ...
Connecting to power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)|52.92.133.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14942564 (14M) [application/x-netcdf]
Saving to: ‘latest_month_geo.nc’

latest_month_geo.nc 100%[===================>]  14,25M  6,23MB/s    in 2,3s

2023-04-10 18:08:03 (6,23 MB/s) - ‘latest_month_geo.nc’ saved [14942564/14942564]

In [28]:
# ds = xr.open_dataset('latest_month.nc')
# df = ds.to_dataframe()

ds_geo = xr.open_dataset('flux.nc')
df_geo = ds_geo.to_dataframe()

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

In [172]:
df.head()

                        TOA_SW_DWN  CLRSKY_SFC_SW_DWN  CLRSKY_SFC_LW_DWN  \
lon    lat  time
-180.0 89.0 2022-05-08  394.257812         277.914062         185.750000
       88.0 2022-05-08  394.140625         277.406250         185.289062
       87.0 2022-05-08  393.898438         275.671875         187.054688
       86.0 2022-05-08  393.539062         274.710938         187.382812
       85.0 2022-05-08  393.062500                NaN                NaN

                        ALLSKY_SFC_SW_DWN  ALLSKY_SFC_LW_DWN
lon    lat  time
-180.0 89.0 2022-05-08         277.671875         216.460938
       88.0 2022-05-08         252.742188         208.539062
       87.0 2022-05-08         273.578125         215.953125
       86.0 2022-05-08         274.453125         224.265625
       85.0 2022-05-08         254.898438         233.640625

In [174]:
df_geo.columns

Index(['T10M', 'T2MWET', 'U10M', 'V2M', 'WS10M_RANGE', 'WD2M', 'U50M',
       'T10M_MIN', 'WS2M_MIN', 'WS2M', 'WS10M_MIN', 'WS50M_MIN', 'TQV',
       'HDD10', 'CDD0', 'RHOA', 'WD50M', 'TS', 'FROST_DAYS', 'T10M_RANGE',
       'QV10M', 'T10M_MAX', 'CDD10', 'T2M', 'T2MDEW', 'TROPPB', 'U2M',
       'WS50M_RANGE', 'WS10M_MAX', 'WS50M_MAX', 'PS', 'WD10M', 'TS_MIN',
       'FRSEAICE', 'QV2M', 'CDD18_3', 'HDD0', 'TO3', 'V50M', 'TROPQ', 'RH2M',
       'TROPT', 'V10M', 'TS_MAX', 'WS2M_MAX', 'T2M_RANGE', 'WS2M_RANGE',
       'TS_RANGE', 'T2M_MIN', 'T2M_MAX', 'WS50M', 'WS10M', 'PRECTOTCORR',
       'DISPH', 'HDD18_3'],
      dtype='object')

In [166]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 207936 entries, (-180.0, -90.0, Timestamp('2022-05-08 00:00:00')) to (179.375, 90.0, Timestamp('2022-05-08 00:00:00'))
Data columns (total 55 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   T10M         207936 non-null  float64
 1   T2MWET       207936 non-null  float64
 2   U10M         207936 non-null  float64
 3   V2M          207936 non-null  float64
 4   WS10M_RANGE  207936 non-null  float64
 5   WD2M         207936 non-null  float64
 6   U50M         207936 non-null  float64
 7   T10M_MIN     207936 non-null  float64
 8   WS2M_MIN     207936 non-null  float64
 9   WS2M         207936 non-null  float64
 10  WS10M_MIN    207936 non-null  float64
 11  WS50M_MIN    207936 non-null  float64
 12  TQV          207936 non-null  float64
 13  HDD10        207936 non-null  float64
 14  CDD0         207936 non-null  float64
 15  RHOA         207936 non-null  float64
 16  WD50M        207936 non-null  float64
 17  TS           207936 non-null  float64
 18  FROST_DAYS   207936 non-null  timedelta64[ns]
 19  T10M_RANGE   207936 non-null  float64
 20  QV10M        207936 non-null  float64
 21  T10M_MAX     207936 non-null  float64
 22  CDD10        207936 non-null  float64
 23  T2M          207936 non-null  float64
 24  T2MDEW       207936 non-null  float64
 25  TROPPB       207936 non-null  float64
 26  U2M          207936 non-null  float64
 27  WS50M_RANGE  207936 non-null  float64
 28  WS10M_MAX    207936 non-null  float64
 29  WS50M_MAX    207936 non-null  float64
 30  PS           207936 non-null  float64
 31  WD10M        207936 non-null  float64
 32  TS_MIN       207936 non-null  float64
 33  FRSEAICE     207936 non-null  float64
 34  QV2M         207936 non-null  float64
 35  CDD18_3      207936 non-null  float64
 36  HDD0         207936 non-null  float64
 37  TO3          207936 non-null  float64
 38  V50M         207936 non-null  float64
 39  TROPQ        207936 non-null  float64
 40  RH2M         207936 non-null  float64
 41  TROPT        207936 non-null  float64
 42  V10M         207936 non-null  float64
 43  TS_MAX       207936 non-null  float64
 44  WS2M_MAX     207936 non-null  float64
 45  T2M_RANGE    207936 non-null  float64
 46  WS2M_RANGE   207936 non-null  float64
 47  TS_RANGE     207936 non-null  float64
 48  T2M_MIN      207936 non-null  float64
 49  T2M_MAX      207936 non-null  float64
 50  WS50M        207936 non-null  float64
 51  WS10M        207936 non-null  float64
 52  PRECTOTCORR  207936 non-null  float64
 53  DISPH        207936 non-null  float64
 54  HDD18_3      207936 non-null  float64
dtypes: float64(54), timedelta64[ns](1)
memory usage: 88.3 MB

In [150]:
df.reset_index()["time"].max()

Timestamp('2022-05-08 00:00:00')

In [151]:
df.reset_index()["time"].min()

Timestamp('2022-05-08 00:00:00')

In [123]:
ds = xr.open_dataset('latest.nc')
df = ds.to_dataframe()
# df = df.iloc[:10000] # limit size

In [124]:
df_flat = df.reset_index()
df_flat.head(2)

,lon,lat,time,ALLSKY_SFC_PAR_TOT,TOA_SW_DWN,ALLSKY_SFC_PAR_DIFF,ALLSKY_SFC_LW_UP,AOD_55_ADJ,ALLSKY_SFC_SW_DIFF,TS_ADJ,...,ALLSKY_SFC_SW_UP,SKY_BRIGHTNESS,CLRSKY_SFC_PAR_DIRH,CLRSKY_SFC_LW_UP,CLRSKY_DAYS,SZA,PW,SRF_ALB_ADJ,ALLSKY_SRF_ALB,AIRMASS
0,-179.5,89.5,2022-05-08 00:00:00,131.875000,405.273438,117.625000,285.953125,0.046875,204.226562,266.828125,...,192.921875,1.640625,83.023438,285.421875,0 days,72.351562,0.500000,0.734375,0.710938,3.257812
1,-179.5,89.5,2022-05-08 01:00:00,121.953125,404.500000,112.296875,268.625000,0.046875,203.414062,262.585938,...,182.476562,1.640625,82.398438,268.046875,0 days,72.382812,0.507812,0.726562,0.703125,3.265625

In [125]:
df_flat["geo_id"] = df_flat.index
df_flat;

In [126]:
df_flat["CLRSKY_DAYS"] = df_flat["CLRSKY_DAYS"].astype(str)

# Point(lat,long)
df_flat["COORDS"] = df_flat.apply(lambda row: Point(row["lat"], row["lon"]).wkb, axis = 1)

In [127]:
# cols = ",".join("st_geogfromtext(geometry, make_valid => TRUE) as geometry" if col == "geometry" else col for col in df)
# query = f"CREATE OR REPLACE TABLE {table_id} AS SELECT {cols} FROM {table_id}"
# # print(query)
# query_job = client.query(query)

In [114]:
#determine schema
type_dict = {
    'b' : 'BOOLEAN',
    'i' : 'INTEGER',
    'f' : 'FLOAT',
    'O' : 'STRING',
    'S' : 'STRING',
    'U' : 'STRING',
    'M': 'TIMESTAMP'
}

schema = [
    {
        'name' : col_name, 
        'type' : "GEOGRAPHY" if col_name == "COORDS" else type_dict.get(col_type.kind, 'STRING')
    } for (col_name, col_type) in df_flat.dtypes.iteritems()
]

df_json = pd.DataFrame({
    col: (df_flat[col] if col != 'COORDS' else df_flat[col].map(lambda x: json.dumps(shapely.geometry.mapping(make_valid(x)))))
    for col in df_flat
})

# for (col_name, col_type) in df_flat.dtypes.iteritems():
#     print("================")
#     print(col_name)
#     print(col_type)
#     print(col_type.kind)

schema

/var/folders/bh/vd0sd4p93kb7zx7q_kj90vgh0000gp/T/ipykernel_95544/2567984364.py:16: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  } for (col_name, col_type) in df_flat.dtypes.iteritems()

[{'name': 'lon', 'type': 'FLOAT'},
 {'name': 'lat', 'type': 'FLOAT'},
 {'name': 'time', 'type': 'TIMESTAMP'},
 {'name': 'ALLSKY_SFC_PAR_TOT', 'type': 'FLOAT'},
 {'name': 'TOA_SW_DWN', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_PAR_DIFF', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_LW_UP', 'type': 'FLOAT'},
 {'name': 'AOD_55_ADJ', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DIFF', 'type': 'FLOAT'},
 {'name': 'TS_ADJ', 'type': 'FLOAT'},
 {'name': 'CLRSKY_NKT', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_SW_DIRH', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SRF_ALB', 'type': 'FLOAT'},
 {'name': 'GLOBAL_ILLUMINANCE', 'type': 'FLOAT'},
 {'name': 'CLOUD_OD', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_SW_DIFF', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DWN', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_PAR_DIFF', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_LW_DWN', 'type': 'FLOAT'},
 {'name': 'TOA_SW_DNI', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DIRH', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_UVA', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_SW_DNI', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_SW_DWN', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_PAR_DIRH', 'type': 'FLOAT'},
 {'name': 'ALLSKY_NKT', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DIFF_ORIGINAL', 'type': 'FLOAT'},
 {'name': 'SKY_CLEARNESS', 'type': 'FLOAT'},
 {'name': 'ALLSKY_KT', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_PAR_TOT', 'type': 'FLOAT'},
 {'name': 'DIRECT_ILLUMINANCE', 'type': 'FLOAT'},
 {'name': 'CLOUD_AMT', 'type': 'FLOAT'},
 {'name': 'AOD_84', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_SW_UP', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_LW_DWN', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_UV_INDEX', 'type': 'FLOAT'},
 {'name': 'ZENITH_LUMINANCE', 'type': 'FLOAT'},
 {'name': 'DIFFUSE_ILLUMINANCE', 'type': 'FLOAT'},
 {'name': 'AOD_55', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_UVB', 'type': 'FLOAT'},
 {'name': 'SKY_CLEARNESS_CAT', 'type': 'FLOAT'},
 {'name': 'CLRSKY_KT', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DWN_ORIGINAL', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_DNI', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SFC_SW_UP', 'type': 'FLOAT'},
 {'name': 'SKY_BRIGHTNESS', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_PAR_DIRH', 'type': 'FLOAT'},
 {'name': 'CLRSKY_SFC_LW_UP', 'type': 'FLOAT'},
 {'name': 'CLRSKY_DAYS', 'type': 'STRING'},
 {'name': 'SZA', 'type': 'FLOAT'},
 {'name': 'PW', 'type': 'FLOAT'},
 {'name': 'SRF_ALB_ADJ', 'type': 'FLOAT'},
 {'name': 'ALLSKY_SRF_ALB', 'type': 'FLOAT'},
 {'name': 'AIRMASS', 'type': 'FLOAT'},
 {'name': 'COORDS', 'type': 'GEOGRAPHY'}]

In [128]:
df_flat["COORDS"] = df_flat["COORDS"].astype(str)
df_flat["COORDS"].head()
df_flat.columns

Index(['lon', 'lat', 'time', 'ALLSKY_SFC_PAR_TOT', 'TOA_SW_DWN',
       'ALLSKY_SFC_PAR_DIFF', 'ALLSKY_SFC_LW_UP', 'AOD_55_ADJ',
       'ALLSKY_SFC_SW_DIFF', 'TS_ADJ', 'CLRSKY_NKT', 'CLRSKY_SFC_SW_DIRH',
       'CLRSKY_SRF_ALB', 'GLOBAL_ILLUMINANCE', 'CLOUD_OD',
       'CLRSKY_SFC_SW_DIFF', 'ALLSKY_SFC_SW_DWN', 'CLRSKY_SFC_PAR_DIFF',
       'ALLSKY_SFC_LW_DWN', 'TOA_SW_DNI', 'ALLSKY_SFC_SW_DIRH',
       'ALLSKY_SFC_UVA', 'CLRSKY_SFC_SW_DNI', 'CLRSKY_SFC_SW_DWN',
       'ALLSKY_SFC_PAR_DIRH', 'ALLSKY_NKT', 'ALLSKY_SFC_SW_DIFF_ORIGINAL',
       'SKY_CLEARNESS', 'ALLSKY_KT', 'CLRSKY_SFC_PAR_TOT',
       'DIRECT_ILLUMINANCE', 'CLOUD_AMT', 'AOD_84', 'CLRSKY_SFC_SW_UP',
       'CLRSKY_SFC_LW_DWN', 'ALLSKY_SFC_UV_INDEX', 'ZENITH_LUMINANCE',
       'DIFFUSE_ILLUMINANCE', 'AOD_55', 'ALLSKY_SFC_UVB', 'SKY_CLEARNESS_CAT',
       'CLRSKY_KT', 'ALLSKY_SFC_SW_DWN_ORIGINAL', 'ALLSKY_SFC_SW_DNI',
       'ALLSKY_SFC_SW_UP', 'SKY_BRIGHTNESS', 'CLRSKY_SFC_PAR_DIRH',
       'CLRSKY_SFC_LW_UP', 'CLRSKY_DAYS', 'SZA', 'PW', 'SRF_ALB_ADJ',
       'ALLSKY_SRF_ALB', 'AIRMASS', 'geo_id', 'COORDS'],
      dtype='object')

In [135]:
df_flat[df_flat["TOA_SW_DNI"] != 0.0].shape

(791529, 56)

In [177]:
start_date = "2021-12-01"
end_date = "2021-12-06"
daterange = pd.date_range(start_date, end_date)

for date in daterange:
    print(date.day)

1
2
3
4
5
6

In [180]:
import os
dt = "2022-05-08"
timestamp = pd.to_datetime("2022-05-10", format='%Y-%m-%d')
year = timestamp.year
month = timestamp.month
day = timestamp.day
url = f"https://power-datastore.s3.amazonaws.com/v9/daily/{year}/{month:02}/power_901_daily_{datetime}_geos5124_utc.nc"
# os.system(f"wget -O latest.nc {url}")
print(url)

https://power-datastore.s3.amazonaws.com/v9/daily/2022/05/power_901_daily_20220508_geos5124_utc.nc

In [184]:
!wget -O monthy.nc https://power-datastore.s3.amazonaws.com/v9/monthly/2021/power_901_monthly_2021_power_hourly_utc.nc

--2023-04-10 18:51:45--  https://power-datastore.s3.amazonaws.com/v9/monthly/2021/power_901_monthly_2021_power_hourly_utc.nc
Resolving power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)... 52.92.240.41, 52.218.192.146, 52.218.244.202, ...
Connecting to power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)|52.92.240.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87092202 (83M) [application/x-netcdf]
Saving to: ‘monthy.nc’

monthy.nc           100%[===================>]  83,06M   730KB/s    in 5m 15s

2023-04-10 18:57:01 (270 KB/s) - ‘monthy.nc’ saved [87092202/87092202]

In [185]:
ds_m = xr.open_dataset('monthy.nc')
df_m = ds_m.to_dataframe()
df_m.head()

                  CLOUD_OD_11  ALLSKY_SFC_SW_DWN_19  CLOUD_OD_02  CLOUD_OD_05  \
lon    lat  time
-179.5 89.5 0.0      4.859375              0.000000     5.304688     4.562500
            1.0      4.375000              0.000000     4.335938     4.195312
            2.0      3.625000             11.875000     3.664062     3.312500
            3.0      2.398438            170.171875     2.539062     2.007812
            4.0      2.789062            319.648438     2.906250     3.117188

                  CLOUD_AMT_11  ALLSKY_SFC_SW_DWN_04  ALLSKY_SFC_SW_DWN_01  \
lon    lat  time
-179.5 89.5 0.0      57.101562              0.000000              0.000000
            1.0      76.171875              0.000000              0.000000
            2.0      56.453125             11.656250             12.734375
            3.0      64.632812            163.648438            156.687500
            4.0      82.468750            296.093750            317.906250

                  CLOUD_OD_12  ALLSKY_SFC_SW_DWN_18  CLOUD_OD_13  ...  \
lon    lat  time                                                  ...
-179.5 89.5 0.0      4.726562              0.000000     4.492188  ...
            1.0      4.687500              0.000000     4.468750  ...
            2.0      3.546875             11.109375     3.414062  ...
            3.0      2.343750            172.703125     2.265625  ...
            4.0      2.867188            324.375000     2.984375  ...

                  CLOUD_OD_17  CLOUD_AMT_09  ALLSKY_SFC_SW_DWN_05  \
lon    lat  time
-179.5 89.5 0.0      4.492188     55.132812              0.000000
            1.0      4.281250     78.343750              0.000000
            2.0      3.500000     55.585938             11.054688
            3.0      2.281250     67.929688            166.812500
            4.0      3.679688     80.421875            303.375000

                  ALLSKY_SFC_SW_DWN_11  ALLSKY_SFC_SW_DWN_21  CLOUD_AMT_15  \
lon    lat  time
-179.5 89.5 0.0               0.000000              0.000000     61.093750
            1.0               0.000000              0.000000     75.562500
            2.0               8.960938             13.171875     61.062500
            3.0             151.695312            174.796875     67.070312
            4.0             289.468750            308.484375     81.960938

                  ALLSKY_SFC_SW_DWN_15  CLOUD_OD_07  ALLSKY_SFC_SW_DWN_13  \
lon    lat  time
-179.5 89.5 0.0               0.000000     4.492188              0.000000
            1.0               0.000000     4.484375              0.000000
            2.0               9.148438     3.539062              8.507812
            3.0             159.531250     1.781250            148.789062
            4.0             294.898438     3.054688            293.960938

                  ALLSKY_SFC_SW_DWN_16
lon    lat  time
-179.5 89.5 0.0               0.000000
            1.0               0.000000
            2.0               9.906250
            3.0             166.062500
            4.0             309.289062

[5 rows x 72 columns]

In [186]:
pd.read_csv("worldcities.csv", sep=",").head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629

In [11]:
# !wget -O flash_flux.nc https://power-datastore.s3.amazonaws.com/v9/daily/2022/01/power_901_daily_20220114_flashflux_lst.nc
# !wget -O ceres.nc https://power-datastore.s3.amazonaws.com/v9/daily/2022/01/power_901_daily_20220115_ceres_lst.nc
!wget -O geo.nc https://power-datastore.s3.amazonaws.com/v9/daily/2023/04/power_901_daily_20230410_geos5124_utc.nc

--2023-04-15 12:11:05--  https://power-datastore.s3.amazonaws.com/v9/daily/2023/04/power_901_daily_20230410_geos5124_utc.nc
Resolving power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)... 52.92.241.65, 52.218.250.19, 52.218.132.107, ...
Connecting to power-datastore.s3.amazonaws.com (power-datastore.s3.amazonaws.com)|52.92.241.65|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14975446 (14M) [application/x-netcdf]
Saving to: ‘geo.nc’

geo.nc              100%[===================>]  14,28M  4,84MB/s    in 3,0s

2023-04-15 12:11:09 (4,84 MB/s) - ‘geo.nc’ saved [14975446/14975446]

In [5]:
flash_flush = xr.open_dataset('flash_flux.nc')
ff_df = flash_flush.to_dataframe()
ff_df.head()

                        TOA_SW_DWN  CLRSKY_SFC_LW_DWN  ALLSKY_SFC_LW_DWN  \
lon    lat  time
-180.0 89.0 2022-01-14         0.0                NaN         219.617188
       88.0 2022-01-14         0.0                NaN         223.718750
       87.0 2022-01-14         0.0                NaN         229.015625
       86.0 2022-01-14         0.0                NaN         228.937500
       85.0 2022-01-14         0.0                NaN         230.359375

                        CLRSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DWN
lon    lat  time
-180.0 89.0 2022-01-14                NaN                NaN
       88.0 2022-01-14                NaN                NaN
       87.0 2022-01-14                NaN                NaN
       86.0 2022-01-14                NaN                NaN
       85.0 2022-01-14                NaN                NaN

In [10]:
ff_df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 64800 entries, (-180.0, 89.0, Timestamp('2022-01-14 00:00:00')) to (179.0, -90.0, Timestamp('2022-01-14 00:00:00'))
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TOA_SW_DWN         62737 non-null  float64
 1   CLRSKY_SFC_LW_DWN  23020 non-null  float64
 2   ALLSKY_SFC_LW_DWN  64800 non-null  float64
 3   CLRSKY_SFC_SW_DWN  14955 non-null  float64
 4   ALLSKY_SFC_SW_DWN  55712 non-null  float64
dtypes: float64(5)
memory usage: 2.8 MB

In [9]:
ceres = xr.open_dataset('ceres.nc')
ceres_df = ceres.to_dataframe()
ceres_df.head()

                          AOD_55  SKY_BRIGHTNESS  ALLSKY_SFC_UV_INDEX  \
lon    lat  time
-179.5 89.5 2022-01-15  0.007812             NaN                  0.0
       88.5 2022-01-15  0.007812             NaN                  0.0
       87.5 2022-01-15  0.007812             NaN                  0.0
       86.5 2022-01-15  0.007812             NaN                  0.0
       85.5 2022-01-15  0.000000             NaN                  0.0

                        CLRSKY_SFC_PAR_TOT  CLRSKY_SFC_SW_DIRH  AOD_55_ADJ  \
lon    lat  time
-179.5 89.5 2022-01-15                 0.0                 0.0    0.007812
       88.5 2022-01-15                 0.0                 0.0    0.007812
       87.5 2022-01-15                 0.0                 0.0    0.007812
       86.5 2022-01-15                 0.0                 0.0    0.007812
       85.5 2022-01-15                 0.0                 0.0    0.000000

                        ALLSKY_SFC_SW_UP  MIDDAY_INSOL  ALLSKY_SFC_SW_DNI  \
lon    lat  time
-179.5 89.5 2022-01-15               0.0           0.0                0.0
       88.5 2022-01-15               0.0           0.0                0.0
       87.5 2022-01-15               0.0           0.0                0.0
       86.5 2022-01-15               0.0           0.0                0.0
       85.5 2022-01-15               0.0           0.0                0.0

                        CLRSKY_SFC_LW_UP  ...   SRF_ALB_ADJ  \
lon    lat  time                          ...
-179.5 89.5 2022-01-15        207.929688  ...  3.402823e+38
       88.5 2022-01-15        207.992188  ...  3.402823e+38
       87.5 2022-01-15        204.179688  ...  3.402823e+38
       86.5 2022-01-15        201.867188  ...  3.402823e+38
       85.5 2022-01-15        204.812500  ...  3.402823e+38

                        ALLSKY_SFC_SW_DIRH  ALLSKY_SFC_LW_DWN  \
lon    lat  time
-179.5 89.5 2022-01-15                 0.0         199.976562
       88.5 2022-01-15                 0.0         185.039062
       87.5 2022-01-15                 0.0         174.984375
       86.5 2022-01-15                 0.0         156.843750
       85.5 2022-01-15                 0.0         178.539062

                        ALLSKY_SFC_SW_DWN  CLOUD_AMT_NIGHT  \
lon    lat  time
-179.5 89.5 2022-01-15                0.0        84.062500
       88.5 2022-01-15                0.0        76.429688
       87.5 2022-01-15                0.0        47.882812
       86.5 2022-01-15                0.0        23.250000
       85.5 2022-01-15                0.0        54.562500

                        ALLSKY_SFC_PAR_TOT  CLRSKY_SFC_SW_DNI  \
lon    lat  time
-179.5 89.5 2022-01-15                 0.0                0.0
       88.5 2022-01-15                 0.0                0.0
       87.5 2022-01-15                 0.0                0.0
       86.5 2022-01-15                 0.0                0.0
       85.5 2022-01-15                 0.0                0.0

                        SKY_CLEARNESS_CAT  CLRSKY_SFC_PAR_DIFF  \
lon    lat  time
-179.5 89.5 2022-01-15      -2.147484e+09                  0.0
       88.5 2022-01-15      -2.147484e+09                  0.0
       87.5 2022-01-15      -2.147484e+09                  0.0
       86.5 2022-01-15      -2.147484e+09                  0.0
       85.5 2022-01-15      -2.147484e+09                  0.0

                        GLOBAL_ILLUMINANCE
lon    lat  time
-179.5 89.5 2022-01-15                 NaN
       88.5 2022-01-15                 NaN
       87.5 2022-01-15                 NaN
       86.5 2022-01-15                 NaN
       85.5 2022-01-15                 NaN

[5 rows x 54 columns]

In [7]:
ceres_df.columns

Index(['AOD_55', 'SKY_BRIGHTNESS', 'ALLSKY_SFC_UV_INDEX', 'CLRSKY_SFC_PAR_TOT',
       'CLRSKY_SFC_SW_DIRH', 'AOD_55_ADJ', 'ALLSKY_SFC_SW_UP', 'MIDDAY_INSOL',
       'ALLSKY_SFC_SW_DNI', 'CLRSKY_SFC_LW_UP', 'CLRSKY_SFC_PAR_DIRH',
       'CLRSKY_NKT', 'ALLSKY_KT', 'CLOUD_AMT_DAY', 'TS_ADJ', 'CLRSKY_SRF_ALB',
       'PW', 'CLRSKY_SFC_SW_UP', 'TOA_SW_DWN', 'AIRMASS', 'SKY_CLEARNESS',
       'CLRSKY_DAYS', 'CLOUD_AMT', 'ALLSKY_SFC_PAR_DIFF', 'TOA_SW_DNI',
       'SG_NOON', 'CLRSKY_SFC_LW_DWN', 'CLRSKY_KT', 'CLRSKY_SFC_SW_DIFF',
       'ALLSKY_SFC_LW_UP', 'SG_DAY_HOURS', 'AOD_84', 'ALLSKY_SFC_UVB',
       'CLRSKY_SFC_SW_DWN', 'CLOUD_OD', 'ALLSKY_SFC_PAR_DIRH',
       'ALLSKY_SFC_UVA', 'ZENITH_LUMINANCE', 'ALLSKY_SRF_ALB', 'SZA',
       'ALLSKY_SFC_SW_DIFF', 'ALLSKY_NKT', 'DIRECT_ILLUMINANCE',
       'DIFFUSE_ILLUMINANCE', 'SRF_ALB_ADJ', 'ALLSKY_SFC_SW_DIRH',
       'ALLSKY_SFC_LW_DWN', 'ALLSKY_SFC_SW_DWN', 'CLOUD_AMT_NIGHT',
       'ALLSKY_SFC_PAR_TOT', 'CLRSKY_SFC_SW_DNI', 'SKY_CLEARNESS_CAT',
       'CLRSKY_SFC_PAR_DIFF', 'GLOBAL_ILLUMINANCE'],
      dtype='object')

In [13]:
geo = xr.open_dataset('geo.nc')
geo_df = geo.to_dataframe()
geo_df.head().T

lon                   -180.0                                    \
lat                    -90.0            -89.5            -89.0
time              2023-04-10       2023-04-10       2023-04-10
V10M                2.773438           2.4375         2.726562
T2M_MIN           209.359375       208.859375       209.484375
FROST_DAYS   1 days 00:00:00  1 days 00:00:00  1 days 00:00:00
T10M_RANGE          3.226562         2.953125         2.578125
CDD18_3                  0.0              0.0              0.0
T10M_MIN          211.070312       211.632812       212.757812
TS                  206.9375       205.328125        204.96875
FRSEAICE                 0.0              0.0              0.0
T2M               210.796875         210.3125       210.921875
WS2M_MAX            3.054688          2.21875         2.226562
WS50M_MIN           5.960938         5.046875         4.578125
TS_MIN              206.0625          204.375         204.0625
T2MDEW            210.796875         210.3125       210.921875
WD50M               227.5625           227.75          219.125
V2M                 1.757812         1.367188         1.609375
WS10M_MIN                4.0         3.617188            3.375
TS_MAX            208.382812       206.632812       206.320312
TROPT             218.085938        218.65625         219.3125
U2M                 2.015625         1.578125         1.335938
WS2M_MIN                 2.5           2.0625         2.039062
HDD18_3              80.6875          81.3125            80.75
HDD0                 62.4375          63.0625          62.4375
WS10M_RANGE           0.5625         0.304688         0.515625
QV10M                    0.0              0.0              0.0
TO3               242.171875       241.351562       239.679688
T10M_MAX          214.289062       214.585938       215.328125
TROPPB            35748.6875        35731.375          35518.0
TROPQ               0.000031         0.000031         0.000031
RH2M                   100.0            100.0            100.0
WS50M_RANGE         0.710938         0.609375         0.914062
WS10M                 4.1875         3.726562         3.585938
WS2M                2.679688         2.101562         2.109375
HDD10                72.4375          73.0625          72.4375
DISPH                    0.0              0.0              0.0
PS                   68156.5       67401.8125        66297.125
WS50M_MAX           6.671875          5.65625         5.492188
V50M                4.203125         3.515625         3.789062
CDD10                    0.0              0.0              0.0
T2M_RANGE           2.757812              2.5         2.460938
T2MWET            210.796875         210.3125       210.921875
WD10M                  228.5         228.8125          220.125
WS10M_MAX             4.5625         3.921875         3.898438
QV2M                     0.0              0.0              0.0
WD2M                 229.125          229.375          219.875
TS_RANGE            2.320312         2.257812         2.257812
U10M                   3.125         2.773438         2.273438
PRECTOTCORR              0.0              0.0              0.0
TQV                 0.296875         0.296875         0.296875
WS50M               6.226562             5.25          4.90625
U50M                4.570312          3.84375         3.046875
CDD0                     0.0              0.0              0.0
T10M              213.046875         213.4375        214.21875
WS2M_RANGE            0.5625          0.15625         0.179688
RHOA                1.104492         1.089844         1.069336
T2M_MAX              212.125       211.359375       211.953125

lon
lat                    -88.5            -88.0
time              2023-04-10       2023-04-10
V10M                4.039062          5.09375
T2M_MIN           212.234375       217.171875
FROST_DAYS   1 days 00:00:00  1 days 00:00:00
T10M_RANGE           2.46875          1.96875
CDD18_3                  0.0              0.0
T10M_MIN          215.695312       219.070312
TS                 207.03125        212.71875
FRSEAICE                 0.0              0.0
T2M               213.703125          217.625
WS2M_MAX            2.742188         4.148438
WS50M_MIN           5.046875           8.5625
TS_MIN            206.359375       212.148438
T2MDEW            213.703125          217.625
WD50M                  173.5            149.5
V2M                 2.421875              3.0
WS10M_MIN           3.671875         5.648438
TS_MAX            208.382812       213.695312
TROPT             219.664062       219.320312
U2M                -0.195312        -1.726562
WS2M_MIN            2.273438           3.1875
HDD18_3                 78.0           73.875
HDD0                 59.6875           55.625
WS10M_RANGE          1.09375         0.765625
QV10M                    0.0              0.0
TO3               238.664062       238.953125
T10M_MAX           218.15625        221.03125
TROPPB             34731.375          32746.0
TROPQ               0.000031         0.000031
RH2M                   100.0            100.0
WS50M_RANGE           1.9375          1.90625
WS10M               4.054688         5.890625
WS2M                2.429688          3.46875
HDD10                69.6875           65.625
DISPH                    0.0              0.0
PS                 65255.125          65208.5
WS50M_MAX           6.984375        10.476562
V50M                5.679688          7.90625
CDD10                    0.0              0.0
T2M_RANGE           2.398438         0.757812
T2MWET            213.703125          217.625
WD10M                175.125         149.9375
WS10M_MAX           4.765625          6.40625
QV2M                     0.0              0.0
WD2M                175.5625         149.9375
TS_RANGE            2.023438         1.546875
U10M               -0.351562          -2.9375
PRECTOTCORR              0.0              0.0
TQV                 0.289062         0.289062
WS50M               5.726562           9.1875
U50M                -0.65625        -4.648438
CDD0                     0.0              0.0
T10M              217.171875         220.4375
WS2M_RANGE           0.46875         0.960938
RHOA                1.037109         1.016602
T2M_MAX           214.632812         217.9375

# Cities data exploring

In [3]:
cities = pd.read_csv("worldcities.csv")

In [5]:
cities[cities["city_ascii"] == "Ibague"]

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
1462,Ibagué,Ibague,4.4333,-75.2333,Colombia,CO,COL,Tolima,admin,541101.0,1170245063

In [26]:
cities

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
...,...,...,...,...,...,...,...,...,...,...,...
44686,Numto,Numto,63.6667,71.3333,Russia,RU,RUS,Khanty-Mansiyskiy Avtonomnyy Okrug-Yugra,NaN,10.0,1643985006
44687,Nord,Nord,81.7166,-17.8000,Greenland,GL,GRL,NaN,NaN,10.0,1304217709
44688,Timmiarmiut,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,Kujalleq,NaN,10.0,1304206491
44689,San Rafael,San Rafael,-16.7795,-60.6799,Bolivia,BO,BOL,Santa Cruz,NaN,NaN,1068405265
44690,Nordvik,Nordvik,74.0165,111.5100,Russia,RU,RUS,Krasnoyarskiy Kray,NaN,0.0,1643587468

In [21]:
cities[cities["population"] > 10000].shape

(38500, 11)

In [6]:
url = "https://power-datastore.s3.amazonaws.com/v9/daily/2023/04/power_901_daily_20230412_geos5124_utc.nc"
r = requests.get(url, allow_redirects=True)

In [37]:
r.status_code

200

In [10]:
open('temp.nc', 'wb').write(r.content)
geo = xr.open_dataset('temp.nc').to_dataframe().reset_index()
geo["time"].min()

Timestamp('2023-04-12 00:00:00')

In [11]:
geo["time"].max()

Timestamp('2023-04-12 00:00:00')

In [12]:
geo.reset_index()

,index,lon,lat,time,FRSEAICE,V10M,U50M,CDD18_3,TS_RANGE,WD10M,...,TROPPB,FROST_DAYS,WS2M_MIN,T2M_RANGE,DISPH,T2MWET,U10M,PS,CDD10,V2M
0,0,-180.000,-90.0,2023-04-12,0.000000,4.125000,-0.390625,0.0,10.210938,176.5000,...,30485.8125,1 days,1.976562,9.140625,0.0,214.757812,-0.093750,68863.750,0.0,2.679688
1,1,-180.000,-89.5,2023-04-12,0.000000,3.687500,-0.750000,0.0,11.523438,171.0625,...,30223.1875,1 days,1.937500,9.273438,0.0,212.468750,-0.429688,68047.375,0.0,2.226562
2,2,-180.000,-89.0,2023-04-12,0.000000,3.796875,-2.968750,0.0,12.023438,154.4375,...,29985.8125,1 days,2.429688,8.828125,0.0,212.359375,-1.781250,66882.750,0.0,2.320312
3,3,-180.000,-88.5,2023-04-12,0.000000,4.460938,-6.828125,0.0,11.492188,136.1875,...,29840.5000,1 days,3.937500,8.953125,0.0,215.382812,-4.406250,65776.750,0.0,3.148438
4,4,-180.000,-88.0,2023-04-12,0.000000,6.085938,-9.796875,0.0,12.117188,130.4375,...,29681.8125,1 days,6.601562,11.453125,0.0,222.046875,-7.234375,65642.750,0.0,4.789062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207931,207931,179.375,88.0,2023-04-12,0.992188,-5.031250,6.578125,0.0,4.390625,277.0000,...,31679.1875,1 days,2.843750,4.085938,0.0,253.953125,5.953125,101283.375,0.0,-4.179688
207932,207932,179.375,88.5,2023-04-12,0.992188,-4.820312,5.390625,0.0,4.007812,257.8125,...,31599.1875,1 days,3.000000,3.710938,0.0,254.351562,4.851562,101232.750,0.0,-3.992188
207933,207933,179.375,89.0,2023-04-12,0.992188,-4.343750,4.062500,0.0,3.687500,253.3125,...,31612.5000,1 days,2.742188,3.531250,0.0,254.539062,3.648438,101195.375,0.0,-3.593750
207934,207934,179.375,89.5,2023-04-12,0.992188,-3.179688,2.453125,0.0,3.796875,249.1875,...,31553.8125,1 days,1.843750,3.890625,0.0,254.570312,2.210938,101175.375,0.0,-2.617188
207935,207935,179.375,90.0,2023-04-12,0.992188,-3.023438,1.601562,0.0,4.101562,228.6875,...,31459.1875,1 days,2.367188,4.929688,0.0,254.593750,1.453125,101160.750,0.0,-2.492188